site_name: Coding Interview
theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: amber
  logo: img/icon.png
  favicon: img/icon.png
  language: ru
plugins:
  - search:
      lang:
        - en
        - ru
nav:
  - Главная: index.md
  - Вопросы на собеседовании: content/questions.md


markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format ''
  - pymdownx.tabbed
  - mdx_math
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML